server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://turntable.proxy.rlwy.net:34068/railway
    username: postgres
    password: PxXrjohsXhezCosDpCmXCMpUKuHOPSwa
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Atualiza tabelas automaticamente
    show-sql: true  # Exibe SQL no console
